server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/refactorCode"
    username: ${Username_db}
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true